apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: log
  name: log
spec:
  containers:
  - image: busybox
    name: log-pro
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" >/log/data/output.log  && sleep 3600']
    volumeMounts:
    - mountPath: /log/data/
      name: log-volume
  - image: busybox
    name: log-cus
    command: ['sh', '-c', 'cat /log/data/output.log && sleep 3600']
    volumeMounts:
    - mountPath: /log/data/
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}